### ISSUE TITLE
Add scope to snippets

### ISSUE THREAD

**Issue by Javierieh** [JasonMortonNZ/bs3-sublime-plugin#102]
The snippets have no scope, so by default they show up on any kind of file.

¿Is it worth adding a scope to, say text.html?

I am willing to make a pull request if needed

**Comment by sadrok** [comment]
this is still an issue.. its clobbering the snippets list in all the other syntax environments

**Comment by Javierieh** [comment]
Would either suggest moving on to Atom, or forking and fixing this yourself.

**Comment by sadrok** [comment]
Thanks. Fixed it myself though

**Comment by JasonMortonNZ** [comment]
@Javierieh - The reason the snippets have no scope is because they're used in so many different scopes - not just .html. There are a number of users using the inside JS, PHP, Ruby, Jade and many other file types. For this reason, I've restrained from adding scope, and having to updates all snippets everytime a new scope is required.
